rawdata<-read.table("household_power_consumption.txt", header = TRUE, nrows=100000, sep=";", stringsAsFactors=FALSE)
data<-subset(rawdata, Date=="1/2/2007"| Date == "2/2/2007")
data<-transform(data, Global_active_power=as.numeric(as.character(Global_active_power)))
data$Date<-paste(data$Date, data$Time)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
data$Time<-strptime(paste(data$Date, data$Time), format = "%Y-%m-%d %H:%M:%S")
Sys.setlocale("LC_TIME", "English")
png(file="plot2.png", width = 480, height = 480)
with(data, plot(Time,  Global_active_power, type="l", ylab="Global Active Power(kilowatts)", xlab=""))
dev.off()
