rawdata<-read.table("household_power_consumption.txt", header = TRUE, nrows=100000, sep=";")
data<-subset(rawdata, Date=="1/2/2007"| Date == "2/2/2007")
data<-transform(data, Global_active_power=as.numeric(as.character(Global_active_power)))
data<-transform(data, Sub_metering_1=as.numeric(as.character(Sub_metering_1)))
data<-transform(data, Sub_metering_2=as.numeric(as.character(Sub_metering_2)))
data<-transform(data, Sub_metering_3=as.numeric(as.character(Sub_metering_3)))
data<-transform(data, Global_reactive_power=as.numeric(as.character(Global_reactive_power)))
data<-transform(data, Voltage=as.numeric(as.character(Voltage)))
data$Date<-paste(data$Date, data$Time)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
data$Time<-strptime(paste(data$Date, data$Time), format = "%Y-%m-%d %H:%M:%S")
Sys.setlocale("LC_TIME", "English")
png(file="plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
with(data, plot(Time,  Global_active_power, type="l", ylab="Global Active Power", xlab=""))
with(data, plot(Time,  Voltage, type="l", ylab="Voltage", xlab="datetime"))
with(data, {
  plot(Time, Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
  lines(Time, Sub_metering_2, type="l", col="red")
  lines(Time, Sub_metering_3, type="l", col="blue")
})
legend("topright", pch="-", col=c("black", "red", "blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(data, plot(Time, Global_reactive_power , type="l", ylab="Global_reactive_power", xlab="datetime"))
dev.off()

